#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port3,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           frontLeft,     tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           Motor_FW_Right, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port7,           Motor_FW_Left, tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++++++++
//*-----------------------------Mecanum Drive Code ----------------------------------------------------------
//* Mecanum Drive with Deadzone Thresholds
//*	- This program allows you to remotely control a robot with mecanum wheels.
//*	- The left joystick Y-axis controls the robot's forward and backward movement.
//*	- The left joystick X-axis controls the robot's left and right movement.
//*	- The right joystick X-axis controls the robot's rotation.
//*	- This program incorportes a threshold/deadzone that allows very low Joystick values to be ignored.
//*	  This allows the robot to ignore values from the Joysticks when they fail to center at 0,
//*	  and provides a margin of error for the driver when they only want the robot to move in one axis.
//*
//*	[I/O Port]          [Name]              [Type]                [Description]
//*	Motor Port 2        frontRight          VEX Motor             Front Right motor
//*	Motor Port 3        backRight           VEX Motor             Back Right motor
//*	Motor Port 4        frontLeft           VEX Motor             Front Left motor
//*	Motor Port 5        backLeft            VEX Motor             Back Left motor
//*
//*---------------------------------FlyWheel ----------------------------------------------------------------
//*
//*    An example of flywheel/shooter velocity control using the TBH algorithm
//*    Test system uses two motors with 25:1 gearing to the flywheel.
//*
//*	[I/O Port]          [Name]              [Type]                [Description]
//*	Motor Port 6        Motor_FW_Right      VEX Motor             Right Motor pair shooter
//*	Motor Port 7        Motor_FW_Left       VEX Motor             Left Motor pair shooter
//*
//*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++++++++

//* ------------------------ CONSTANTS ----------------------------------------------------------------------

#define DEBUG true

//* Update inteval (in mS) for the flywheel control loop
#define FW_LOOP_SPEED              25

// Maximum power we want to send to the flywheel motors
#define FW_MAX_POWER              127

// encoder counts per revolution depending on motor
#define MOTOR_TPR_269           240.448
#define MOTOR_TPR_393R          261.333		// HIGH speed
#define MOTOR_TPR_393S          392				// Turbo Mode
#define MOTOR_TPR_393T          627.2			// High Torque - standard config
#define MOTOR_TPR_QUAD          360.0

// Structure to gather all the flywheel ralated data
typedef struct _fw_controller {
    long            counter;                ///< loop counter used for debug

    // encoder tick per revolution
    float           ticks_per_rev;          ///< encoder ticks per revolution

    // Encoder
    long            e_current;              ///< current encoder count
    long            e_last;                 ///< current encoder count

    // velocity measurement
    float           v_current;              ///< current velocity in rpm
    long            v_time;                 ///< Time of last velocity calculation

    // TBH control algorithm variables
    long            target;                 ///< target velocity
    long            current;                ///< current velocity
    long            last;                   ///< last velocity
    float           error;                  ///< error between actual and target velocities
    float           last_error;             ///< error last time update called
    float           gain;                   ///< gain
    float           drive;                  ///< final drive out of TBH (0.0 to 1.0)
    float           drive_at_zero;          ///< drive at last zero crossing
    long            first_cross;            ///< flag indicating first zero crossing
    float           drive_approx;           ///< estimated open loop drive

    // final motor drive
    long            motor_drive;            ///< final motor control value
    } fw_controller;

// Make the controller global for easy debugging
static  fw_controller   flywheel;

//* ========================== FUNCTIONS ====================================================================

/*-----------------------------------------------------------------------------*/
/** @brief      Set the flywheen motors                                        */
/** @param[in]  value motor control value                                      */
/*-----------------------------------------------------------------------------*/
void FwMotorSet( int value )
{
    motor[ Motor_FW_Left ] = value;
    motor[ Motor_FW_Right] = value;
}

/*-----------------------------------------------------------------------------*/
/** @brief      Get the flywheen motor encoder count                           */
/*-----------------------------------------------------------------------------*/
long FwMotorEncoderGet()
{
    return( nMotorEncoder[ Motor_FW_Left ] );
}

/*-----------------------------------------------------------------------------*/
/** @brief      Set the controller position                                    */
/** @param[in]  fw pointer to flywheel controller structure                    */
/** @param[in]  desired velocity                                               */
/** @param[in]  predicted_drive estimated open loop motor drive                */
/*-----------------------------------------------------------------------------*/
void FwVelocitySet( fw_controller *fw, int velocity, float predicted_drive )
{
    // set target velocity (motor rpm)
    fw->target        = velocity;

    // Set error so zero crossing is correctly detected
    fw->error         = fw->target - fw->current;
    fw->last_error    = fw->error;

    // Set predicted open loop drive value
    fw->drive_approx  = predicted_drive;
    // Set flag to detect first zero crossing
    fw->first_cross   = 1;
    // clear tbh variable
    fw->drive_at_zero = 0;
}

/*-----------------------------------------------------------------------------*/
/** @brief      Calculate the current flywheel motor velocity                  */
/** @param[in]  fw pointer to flywheel controller structure                    */
/*-----------------------------------------------------------------------------*/
void FwCalculateSpeed( fw_controller *fw )
{
    int     delta_ms;
    int     delta_enc;

    // Get current encoder value
    fw->e_current = FwMotorEncoderGet();

    // This is just used so we don't need to know how often we are called
    // how many mS since we were last here
    delta_ms   = nSysTime - fw->v_time;
    fw->v_time = nSysTime;

    // Change in encoder count
    delta_enc = (fw->e_current - fw->e_last);

    // save last position
    fw->e_last = fw->e_current;

    // Calculate velocity in rpm
    fw->v_current = (1000.0 / delta_ms) * delta_enc * 60.0 / fw->ticks_per_rev;
}

/*-----------------------------------------------------------------------------*/
/** @brief      Update the velocity tbh controller variables                   */
/** @param[in]  fw pointer to flywheel controller structure                    */
/*-----------------------------------------------------------------------------*/
void FwControlUpdateVelocityTbh( fw_controller *fw )
{
    // calculate error in velocity
    // target is desired velocity
    // current is measured velocity
    fw->error = fw->target - fw->current;

    // Use Kp as gain
    fw->drive =  fw->drive + (fw->error * fw->gain);

    // Clip - we are only going forwards
    if( fw->drive > 1 )
          fw->drive = 1;
    if( fw->drive < 0 )
          fw->drive = 0;

    // Check for zero crossing
    if( sgn(fw->error) != sgn(fw->last_error) ) {
        // First zero crossing after a new set velocity command
        if( fw->first_cross ) {
            // Set drive to the open loop approximation
            fw->drive = fw->drive_approx;
            fw->first_cross = 0;
        }
        else
            fw->drive = 0.5 * ( fw->drive + fw->drive_at_zero );

        // Save this drive value in the "tbh" variable
        fw->drive_at_zero = fw->drive;
    }

    // Save last error
    fw->last_error = fw->error;
}

//* ========================== TASKS ========================================================================

/*-----------------------------------------------------------------------------*/
/** @brief     Task to control the velocity of the flywheel                    */
/*-----------------------------------------------------------------------------*/
task FwControlTask()
{
    fw_controller *fw = &flywheel;

    // Set the gain
    fw->gain = 0.00025;

    // We are using Speed geared motors
    // Set the encoder ticks per revolution
    //fw->ticks_per_rev = MOTOR_TPR_393S;
    fw->ticks_per_rev = MOTOR_TPR_393T;

    while(1)
        {
        // debug counter
        fw->counter++;

        // Calculate velocity
        FwCalculateSpeed( fw );

        // Set current speed for the tbh calculation code
        fw->current = fw->v_current;

        // Do the velocity TBH calculations
        FwControlUpdateVelocityTbh( fw ) ;

        // Scale drive into the range the motors need
        fw->motor_drive  = (fw->drive * FW_MAX_POWER) + 0.5;

        // Final Limit of motor values - don't really need this
        if( fw->motor_drive >  127 ) fw->motor_drive =  127;
        if( fw->motor_drive < -127 ) fw->motor_drive = -127;

        // and finally set the motor control value
        FwMotorSet( fw->motor_drive );

        // Run at somewhere between 20 and 50mS
        wait1Msec( FW_LOOP_SPEED );
        }
}

/*-----------------------------------------------------------------------------*/
/** @brief     Task to drive the robot  - Remote Control #1            				 */
/*-----------------------------------------------------------------------------*/
task driverControlTask()
{
  //Create "deadzone" variables. Adjust threshold value to increase/decrease deadzone
  int X2 = 0, Y1 = 0, X1 = 0, threshold = 15;

  //Loop Forever
  while(1 == 1)
  {
    //Create "deadzone" for Y1/Ch3
    if(abs(vexRT[Ch3]) > threshold)
      Y1 = vexRT[Ch3];
    else
      Y1 = 0;
    //Create "deadzone" for X1/Ch4
    if(abs(vexRT[Ch4]) > threshold)
      X1 = vexRT[Ch4];
    else
      X1 = 0;
    //Create "deadzone" for X2/Ch1
    if(abs(vexRT[Ch1]) > threshold)
      X2 = vexRT[Ch1];
    else
      X2 = 0;

    //Remote Control Commands
    motor[frontRight] = Y1 - X2 - X1;
    motor[backRight] =  Y1 - X2 + X1;
    motor[frontLeft] = Y1 + X2 + X1;
    motor[backLeft] =  Y1 + X2 - X1;

    // Don't hog the cpu :)
    wait1Msec(10);
  }
}

/*-----------------------------------------------------------------------------*/
/** @brief     Task to operate shooter and loader tools - remoteCOntrol #2		 */
/*-----------------------------------------------------------------------------*/
task shooterControlTask()
{
   	char  str[32];
   	char  debugStr[64];

   	// Main user control loop
    while(1)
        {
        // Different speeds set by buttons
        if( vexRT[ Btn8LXmtr2 ] == 1 )
            //FwVelocitySet( &flywheel, 144, 0.55 );
          	FwVelocitySet( &flywheel, 100, 0.55 );			// Full Speed
        if( vexRT[ Btn8UXmtr2 ] == 1 )
            //FwVelocitySet( &flywheel, 120, 0.38 );
						FwVelocitySet( &flywheel, 80, 0.32 );				// Mid Speed
            if( vexRT[ Btn8RXmtr2 ] == 1 )
            FwVelocitySet( &flywheel, 50, 0.2 );				// Half Speed
        if( vexRT[ Btn8DXmtr2 ] == 1 )
            FwVelocitySet( &flywheel, 00, 0 );

        // Display useful things on the LCD
        sprintf( str, "%4d %4d  %5.2f", flywheel.target,  flywheel.current, nImmediateBatteryLevel/1000.0 );
        displayLCDString(0, 0, str );
        sprintf( str, "%4.2f %4.2f ", flywheel.drive, flywheel.drive_at_zero );
        displayLCDString(1, 0, str );

        if(DEBUG) {
        	sprintf( debugStr, "%4d %4d  %5.2f %4.2f %4.2f ", flywheel.target,  flywheel.current, nImmediateBatteryLevel/1000.0, flywheel.drive, flywheel.drive_at_zero );
        	writeDebugStreamLine(debugStr);
        }
        // Don't hog the cpu :)
        wait1Msec(10);
        }
}

//* ========================== MAIN TASK  ===================================================================

task main()
{


    bLCDBacklight = true;

    // Start the flywheel control task
    startTask( FwControlTask );
		startTask( driverControlTask);
		startTask( shooterControlTask);
	  //Loop Forever
  	while(1 == 1)
  	{
	    // Don't hog the cpu :)
      wait1Msec(10);
    }
}
