#pragma config(Motor,  port6,           leftShooter1,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftShooter2,  tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main ()
{

	while(1 == 1)
	{
		// Start / Stop shooter
		if(vexRT[Btn5U] == 1)       	//If button 5U is pressed...
		{
			motor[leftShooter1] = 127;    	//...raise the arm.
			motor[leftShooter2] = 127;
		}
		else
		{
			motor[leftShooter1] = 0;   	//...lower the arm.
			motor[leftShooter2] = 0;
		}
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
